on: [push]

jobs:
  upload_files:
    runs-on: ubuntu-latest
    name: Upload files
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Upload
      uses: Dylan700/sftp-upload-action@v1.2.1
      with:
        server: 13.210.175.221
        username: ubuntu
        delete: true
        key: ${{secrets.key}}
        passphrase: ${{secrets.passphrase}}
        port: 22
        uploads: ./ => /var/www/html/
          
